# Implement your initial tasks here
# -------------------------------------------------

- name: set some vm facts
  set_fact:
    vnet_name: "{{ instance_base_name }}-vm-vnet" # was vpc_name
    subnet_name: "{{ instance_base_name }}-vm-subnet"
    nsg_name: "{{ instance_base_name }}-vm-nsg" # was security_group_name
    
- name: set some ansible facts
  set_fact:
    ssh_public_key_name: "{{ instance_key_name }}"
    ssh_public_key_path: "{{ public_key_dir }}/{{ instance_key_name }}.pub"
    ssh_private_key_path: "{{ public_key_dir }}/{{ instance_key_name }}"
    ansible_user: "{{ instance_default_user }}" # ec2-user, azureuser
    ansible_ssh_private_key_file: "~/.ssh/{{ public_key_dir }}/{{ instance_key_name }}" # private key used to access the remote server
