# Implement your install deployment tasks here
# -------------------------------------------------

- name: create cnv vm instances
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - builder-virtualmachine.yml.j2