# Implement your pre-install deployment tasks here
# -------------------------------------------------

- name: check if the ssh key exists
  stat:
    path: "{{ builder_ssh_key_dir }}/{{ cluster_name }}-vm"
  register: builder_ssh_key_stat

- name: generate ssh keys
  when: builder_ssh_key_stat.stat.exists == false
  openssh_keypair:
    type: rsa
    size: 2048
    path: "{{ builder_ssh_key_dir }}/{{ cluster_name }}-vm"

- name: import the vm private key
  slurp:
    src: "{{ builder_ssh_key_dir }}/{{ cluster_name }}-vm"
  register: vm_ssh_private_key

- name: import the vm public key
  slurp:
    src: "{{ builder_ssh_key_dir }}/{{ cluster_name }}-vm.pub"
  register: vm_ssh_pub_key