# Implement your pre-install deployment tasks here
# -------------------------------------------------

- name: install gitops operator
  include_role:
    name: roles/install-operator
  vars:
    operator_name: "openshift-gitops-operator"
    operator_subscription_name: "openshift-gitops-operator"
    subscription_channel: "{{ gitops_subscription_channel }}"
    subscription_starting_csv: "{{ gitops_subscription_starting_csv }}"
    operator_deployment_name: "openshift-gitops-operator-controller-manager"
    operator_namespace: "openshift-gitops-operator"
    operator_group_name: "openshift-gitops-operator"
    create_operator_namespace: true
    create_operator_group: true

- name: install pipelines operator
  include_role:
    name: roles/install-operator
  vars:
    operator_name: "openshift-pipelines-operator-rh"
    operator_subscription_name: "openshift-pipelines-operator"
    subscription_channel: "{{ pipelines_subscription_channel }}"
    subscription_starting_csv: "{{ pipelines_subscription_starting_csv }}"
    operator_deployment_name: "openshift-pipelines-operator"