# Implement your install deployment tasks here
# -------------------------------------------------

- name: create rhadp app project
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - rhadp-app-project.yml.j2
    - rhadp-app.yml.j2

- name: wait for rhadp-devspaces namespace to be ready
  k8s_info:
    api_version: v1
    kind: Namespace
    name: rhadp-devspaces
    kubeconfig: "{{ local_kubeconfig_file }}"
  register: r_namespace
  retries: 30
  delay: 10
  until:
    - r_namespace.resources | length | int > 0
    - r_namespace.resources[0].status.phase is defined
    - r_namespace.resources[0].status.phase == "Active"

- name: deploy additional devspaces resources
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - devspaces-github-oauth-config.yml.j2

# optional platform features

# devhub

# jumpstarter

- name: setup jumpstarter
  when: rhadp_deploy_jumpstart | bool
  include_role:
    name: roles/setup-jumpstarter

# exporter
