apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: rhadp-devspaces
  #namespace: rhadp-devspaces
  finalizers:
    - checluster.che.eclipse.org
    - cluster-resources.finalizers.che.eclipse.org
    - cheGateway.clusterpermissions.finalizers.che.eclipse.org
    - oauthclients.finalizers.che.eclipse.org
    - dashboard.clusterpermissions.finalizers.che.eclipse.org
    - resources-finalizer.argocd.argoproj.io
spec:
  components:
    cheServer:
      debug: false
      logLevel: INFO
      extraProperties:
        CHE_FORCE_REFRESH_PERSONAL_ACCESS_TOKEN: "true"

    dashboard:
      logLevel: INFO
      #headerMessage:
      #  show: true
      #  text: {{ devspaces_instance_description }}

    devWorkspace: {}

    devfileRegistry: {}
    imagePuller:
      enable: false
      spec: {}
    metrics:
      enable: true
    pluginRegistry: {}

  containerRegistry: {}

  devEnvironments:
    workspacesPodAnnotations:
      io.kubernetes.cri-o.Devices: /dev/fuse

    startTimeoutSeconds: 300
    secondsOfInactivityBeforeIdling: 1800

    security: {}
    secondsOfRunBeforeIdling: -1
    disableContainerBuildCapabilities: false
    containerBuildConfiguration:
      openShiftSecurityContextConstraint: container-build

    ignoredUnrecoverableEvents:
      - FailedScheduling

    maxNumberOfWorkspacesPerUser: -1 # no limit
    maxNumberOfRunningWorkspacesPerUser: 1
    maxNumberOfRunningWorkspacesPerCluster: -1

    #allowedSources:
    #  urls:
    #    - 'https://github.com/*'

    imagePullPolicy: Always
    deploymentStrategy: Recreate

    nodeSelector:
      rhadp.node-role/builder: "true"

    defaultComponents:
      - name: runtime
        container:
          sourceMapping: /projects
          image: "quay.io/rhadp/codespaces:latest"

    defaultNamespace:
      autoProvision: true
      template: "devspaces-<username>"

    storage:
      perUserStrategyPvcConfig:
        claimSize: 5Gi
      pvcStrategy: per-user

  gitServices:
    github:
      - secretName: "github-oauth-config"

  networking:
    auth:
      advancedAuthorization:
        allowGroups:
          - "platform-admins"
          - "platform-users"
      gateway:
        configLabels:
          app: che
          component: che-gateway-config
