# Implement your install deployment tasks here
# -------------------------------------------------

- name: create jumpstarter environment
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - jumpstarter-bootstrap-app.yml.j2

- name: create jumpstarter application
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - jumpstarter-app.yml.j2