# Implement your post-install deployment tasks here
# -------------------------------------------------

- name: create qemu exporters
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml_all }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - qemu-exporter-app.yml.j2
