# Implement your pre-install deployment tasks here
# -------------------------------------------------

- name: install hashicorp vault operator
  include_role:
    name: roles/install-operator
  vars:
    operator_name: "vault-secrets-operator"
    operator_subscription_name: "vault-secrets-operator"
    subscription_channel: "{{ vault_subscription_channel }}"
    subscription_starting_csv: "{{ vault_subscription_starting_csv }}"
    source: "certified-operators"
    operator_deployment_name: "vault-secrets-operator-controller-manager"